dict_metric = {'Cmp': 'Passes Completed',
               'PassAtt': 'Passes Attempted',
               'CmpPct': 'Pass Completion %',
               'PassTotDist': 'Total Pass Distance',
               'PassPrgDist': 'Progressive Pass Distance',
               'Cmp1': 'Passes Completed Short',
               'Att1': 'Passes Attempted Short',
               'CmpPct1': 'Pass Completion % Short',
               'Cmp2': 'Passes Completed Medium',
               'Att2': 'Passes Attempted Medium',
               'CmpPct2': 'Pass Completion % Medium',
               'Cmp3': 'Passes Completed Long',
               'Att3': 'Passes Attempted Long',
               'CmpPct3': 'Pass Completion % Long',
               'Ast': 'Assists',
               'xA': 'Expected Assists',
               'KP': 'Key Passes',
               'PassFinThird': 'Passes into Final Third',
               'PPA': 'Passes into Penalty Area',
               'CrsPA': 'Crosses into Penalty Area',
               'PassProg': 'Progressive Passes',
               'SCA': 'Shot Creating Actions',
               'PassLiveShot': 'Live-ball passes that lead to a shot',
               'PassDeadShot': 'Dead-ball passes that lead to a shot',
               'DribShot': 'Dribbles that lead to a shot',
               'ShLSh': 'Shots that lead to another shot',
               'Fld': 'Fouls drawn that lead to a shot',
               'DefShot': 'Defensive actions that lead to a shot',
               'GCA': 'Goal Creating Actions',
               'PassLiveGoal': 'Live-ball passes that lead to a goal',
               'PassDeadGoal': 'Dead-ball passes that lead to a goal',
               'DribGoal': 'Dribbles that lead to a goal',
               'ShGoal': 'Shots that lead to a goal',
               'FldGoal': 'Fouls drawn that lead to a goal',
               'DefGoal': 'Defensive actions that lead to a goal',
               'OG': 'Own Goals',
               'Tkl': 'Number of players tackled',
               'TklW': 'Number of tackles won',
               'TacklesDef3rd': 'Tackles in Defensive 3rd',
               'TacklesMid3rd': 'Tackles in Middle 3rd',
               'TacklesAtt3rd': 'Tackles in Attacking 3rd',
               'DribTackled': 'Number of times dribbled tackled',
               'DribContest': 'Number of times dribble contested',
               'DribTackledPct': 'Percentage of times dribble tackled',
               'Past': 'Number of times dribbled past',
               'Press': 'Number of times applying pressure',
               'SuccPress': 'Successful pressures',
               'SuccPressPct': 'Percentage of successful pressures',
               'PressDef3rd': 'Pressures in Defensive 3rd',
               'PressMid3rd': 'Pressures in Middle 3rd',
               'PressAtt3rd': 'Pressures in Attacking 3rd',
               'Blocks': 'Number of times blocking the ball',
               'BlockSh': 'Number of times blocking a shot',
               'ShSv': 'Number of times blocking a shot on target',
               'Pass': 'Number of times blocking a pass',
               'Int': 'Interceptions',
               'TklInt': 'Tackles + Interceptions',
               'Clr': 'Clearances',
               'Err': 'Errors leading to a shot',
               'Touches': 'Number of times touched the ball',
               'DefPen': 'Touches in defensive penalty area',
               'TouchDef3rd': 'Touches in defensive 3rd',
               'TouchMid3rd': 'Touches in middle 3rd',
               'TouchAtt3rd': 'Touches in attacking 3rd',
               'AttPen': 'Touches in attacking penalty area',
               'Live': 'Touches live ball',
               'Succ': 'Dribbles Completed Successfully',
               'Att': 'Dribbles Attempted',
               'SuccPct': 'Dribble Success %',
               'NumPl': 'Number of Players Dribbled Past',
               'Megs': 'Number of Times Megged',
               'Carries': 'Number of times carried the ball',
               'TotDist': 'Total Distance Carried',
               'PrgDist': 'Progressive Distance Carried',
               'ProgCarries': 'Progressive Carries',
               'CarriesFinThird': 'Carries into Final Third',
               'CPA': 'Carries into Penalty Area',
               'Mis': 'Miscontrols',
               'Dis': 'Dispossessed',
               'Targ': 'Number of times targeted',
               'Rec': 'Number of times received the ball',
               'RecPct': 'Percentage of times received the ball',
               'ProgPassRec': 'Progressive Passes Received',
               'Gls': 'Goals',
               'PK': 'Penalty Kicks Made',
               'PKatt': 'Penalty Kicks Attempted',
               'Sh': 'Shots total (Exclude PKs)',
               'SoT': 'Shots on Target (Exclude PKs)',
               'CrdY': 'Yellow Cards',
               'CrdR': 'Red Cards',
               'xG': 'Expected Goals',
               'npxG': 'Non-Penalty Expected Goals'}

type_of_stats = {'Passing': ['Cmp', 'PassAtt', 'CmpPct', 'PassTotDist', 'PassPrgDist', 'Cmp1', 'Att1', 'CmpPct1', 'Cmp2', 'Att2', 'CmpPct2', 'Cmp3', 'Att3', 'CmpPct3', 'Ast', 'xA', 'KP', 'PassFinThird', 'PPA', 'CrsPA', 'PassProg'],
                 'Goal and Shot Creation': ['SCA', 'PassLiveShot', 'PassDeadShot', 'DribShot', 'ShLSh', 'Fld', 'DefShot', 'GCA', 'PassLiveGoal', 'PassDeadGoal', 'DribGoal', 'ShGoal', 'FldGoal', 'DefGoal', 'OG'],
                 'Defensive Actions': ['Tkl', 'TklW', 'TacklesDef3rd', 'TacklesMid3rd', 'TacklesAtt3rd', 'DribTackled', 'DribContest', 'DribTackledPct', 'Past', 'Press', 'SuccPress', 'SuccPressPct', 'PressDef3rd', 'PressMid3rd', 'PressAtt3rd', 'Blocks', 'BlockSh', 'ShSv', 'Pass', 'Int', 'TklInt', 'Clr', 'Err'],
                 'Possession': ['Touches', 'Def Pen', 'TouchDef3rd', 'TouchMid3rd', 'TouchAtt3rd', 'AttPen', 'Live', 'Succ', 'Att', 'SuccPct', 'NumPl', 'Megs', 'Carries', 'TotDist', 'PrgDist', 'ProgCarries', 'CarriesFinThird', 'CPA', 'Mis', 'Dis', 'Targ', 'Rec', 'RecPct'],
                 'Summary': ['ProgPassRec', 'Gls', 'PK', 'PKatt', 'Sh', 'SoT', 'CrdY', 'CrdR', 'xG', 'npxG']}